default: &default
  api_key: <%= ENV['BREVO_API_KEY'] %>
  from_email: <%= ENV['BREVO_FROM_EMAIL'] || 'noreply@cerveras.com' %>
  from_name: <%= ENV['BREVO_FROM_NAME'] || 'Curriculum Library' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
