defaults: &defaults
  subdomain: <%= ENV['CLOUDFLARE_SUBDOMAIN'] || 'curriculum' %>
  # Stream management (for video hosting)
  stream_api_token: <%= ENV['CLOUDFLARE_STREAM_API_TOKEN'] %>
  stream_account_id: <%= ENV['CLOUDFLARE_STREAM_ACCOUNT_ID'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
