defaults: &defaults
  domain: cerveras.com
  # These will be overridden by environment variables
  api_token: <%= ENV['CLOUDFLARE_API_TOKEN'] %>
  zone_id: <%= ENV['CLOUDFLARE_ZONE_ID'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
