defaults: &defaults
  domain: cerveras.com
  # These will be overridden by Rails credentials
  api_token: <%= Rails.application.credentials.cloudflare&.dig(:api_token) %>
  zone_id: <%= Rails.application.credentials.cloudflare&.dig(:zone_id) %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
