# config/storage.yml
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  # You can omit these two if relying on AWS default credential chain (env/role).
  access_key_id:     <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region:            <%= ENV["AWS_REGION"] || "us-east-1" %>
  bucket:            <%= ENV["AWS_S3_BUCKET"] %>
  # Leave false (default) for AWS S3; set true for some S3-compatible providers (MinIO/R2).
  force_path_style: false
  # Prefer private objects unless you explicitly want public ACLs
  public: false